apiVersion: v1
kind: Service
metadata:
  # note: include는 helpers.tpl에서 가져오는 값
  # note: helm command입력시 사용한 배포 인스턴스 명이 들어감
  name: {{ include "api-tester.fullname" . }}
  labels:
    {{- include "api-tester.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "api-tester.selectorLabels" . | nindent 4 }}
