apiVersion: v1
kind: Secret
metadata:
  # note: include는 helpers.tpl에서 가져오는 값
  # note: helm command입력시 사용한 배포 인스턴스 명이 들어감
  name: {{ include "api-tester.fullname" . }}-postgresql
  labels:
    {{- include "api-tester.labels" . | nindent 4 }}
stringData:
  # note: values.yaml의 secret.data.postgresql 설정정보가 들어감
  {{- toYaml .Values.secret.data.postgresql | nindent 2 }}